language: java

branches:
  only:
    - master
    - develop

jdk:
  - openjdk15

os: linux
arch:
  - arm64
dist: xenial
before_install:
  - sudo apt-get -yq install openjdk-15-jdk
  - sudo apt-get -yq install maven